### ISSUE TITLE
Yet another GNOME update (v45 compatibility)

### ISSUE THREAD

**Issue by kenohassler** [ethanwharris/gnome-nvidia-extension#212]
## Current Situation

[GNOME changed their API yet again](https://gjs.guide/extensions/upgrading/gnome-shell-45.html), so this time we cannot just bump the version number in metadata.json. I did the minimum necessary changes to get it running in [my fork](https://github.com/kenohassler/gnome-nvidia-extension/tree/gnome45), but the code quality is not great and has not actually been tested on bare metal yet.

## Steps Forward
The switch to ECMAScript modules for gnome 45 breaks backwards compatibility and apparently there is no easy way to fix that. Since all "stable" distros will keep using gnome 40~44 for a while, I'd propose to keep the gnome 45 version in a separate branch. According to documentation, we could release a combined version on extensions.gnome.org to make everyone happy.
Unfortunately, this means any feature / bug patch would have to be applied twice to keep the versions in sync for the near future.

## ToDos

- [ ] Code cleanup & linting
- [ ] Actually test the stuff
- [ ] Find out how to build combined releases

**Comment by kenohassler** [comment]
I added a fix to actually make it work and cleaned up the code. All in all, the change is rather minimal (after you figure know which knobs to turn 😁 )
There is one blocker before we can release a new version: According to the review guidelines, [GTK imports are no longer allowed](https://gjs.guide/extensions/review-guidelines/review-guidelines.html#gtk-and-gdk-imports). We use them to construct the preferences window. Hence, this needs to be ported to libadwaita. I'll have a look at this.

**Comment by moctavianro** [comment]
Please make a 45 version ASAP... Ubuntu and Fedora but not only use it. Thanks!

**Comment by kenohassler** [comment]
Thanks for bumping this. I looked into GTK imports in the past and I think they are not allowed in the main extension, but fine to use in the settings widget. So I think my code is ready to be merged (into a new branch perhaps, since it totally breaks backwards compatibility).

**Comment by kenohassler** [comment]
summonning @ethanwharris here to give this a look and maybe release the update on extensions.gnome.org? 😃

**Comment by derenv** [comment]
Now that #214 and #215 have been merged, we can take the last few steps for a new version on gnome extensions:

- [  ] we should tag the commit and create a new release (v11)
- [  ] We should also tag the legacy branch and create a separate release for this
- [  ] finally, @ethanwharris can add these to [the gnome extensions website](extensions.gnome.org)

**Comment by derenv** [comment]
> summonning @ethanwharris here to give this a look and maybe release the update on extensions.gnome.org? 😃

beat me to it :laughing:

**Comment by ethanwharris** [comment]
Hey @derenv @kenohassler cool! Let me know when you have the tag and I'll upload it for review :)

**Comment by kenohassler** [comment]
perfect. can you take care of the tagging @derenv?

**Comment by derenv** [comment]
@kenohassler @ethanwharris Tags and releases created!

**Comment by ethanwharris** [comment]
@derenv @kenohassler New version and legacy update both in review 😃 Thanks!

**Comment by ethanwharris** [comment]
Hey @derenv @kenohassler Update here, the legacy release was accepted - we have a review for the new version here: https://extensions.gnome.org/review/54304 :)

**Comment by derenv** [comment]
> Hey @derenv @kenohassler Update here, the legacy release was accepted - we have a review for the new version here: https://extensions.gnome.org/review/54304 😄

pull request from @kenohassler merged, tagged and new release created
